# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/27e081eb24419ee843ae1c329b0482db823c9fc1/hyperparams/sac.yml
seed: 42

policy: "MlpPolicy"
n_timesteps: 200000000
learning_starts: 10000
buffer_size: 2000000
train_freq: 1
gradient_steps: 16
batch_size: 4096
gamma: 0.998
tau: 0.005
learning_rate: lin_3e-4
ent_coef: "auto"
target_entropy: "auto"
policy_kwargs: "dict(
  log_std_init=-2,
  share_features_extractor=False,
  net_arch=dict(pi=[2048, 2048], qf=[2048, 2048])
  )"
